name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || '' }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      # Use setup-node's built-in functionality for caching and restoring npm dependencies
      # See: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          # renovate: datasource=node-version depName=node
          node-version: 24.14.1
          cache: 'npm'